name: build-maaxboard-docker

on:
  workflow_dispatch:
jobs:
  build-docker-stm32m1:
    runs-on: [self-hosted, build]
    steps:
      - name: Checkout simplecore-tools
        uses: actions/checkout@v4.1.1
        with:
          path: 'docker'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PAT}}
      - name:  Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: docker/.github/maaxboard-docker
          push: true
          tags: ghcr.io/avnet-iotconnect/meta-iotconnect/maaxboard-iotc-sdk-kirkstone:latest

  clean:
    runs-on: [self-hosted, build]
    if: always()
    needs:
      [
        build-docker-stm32m1
      ]
    steps:
      - name: "clean build dir"
        run: |
          rm -rf docker-msc-ldk/
