name: build-sdk-images

on:
  workflow_dispatch:
    inputs:
      yocto-image:
        description: "The yocto image to build"
        required: false
        default: "st-image-weston"
jobs:
  build-yocto:
    runs-on: [self-hosted, build]
    container:
      image: ghcr.io/avnet-iotconnect/:latest
      options: --user usersetup
    steps:
      - name: Checkout simplecore-tools
        uses: actions/checkout@v4.1.1
        with:
          path: 'STM32MP157_IoTC_kirkstone/layers/meta-iotconnect'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Run yocto build"
        run: |
          cd STM32MP157_IoTC_kirkstone/
          MACHINE=stm32mp1 DISTRO=openstlinux-weston EULA_stm32mp1=1 source layers/meta-st/scripts/envsetup.sh
          cd ../
          source layers/openembedded-core/oe-init-build-env build-openstlinuxweston-stm32mp1
          bitbake-layers add-layer ../layers/meta-iotconnect
          git config --global user.email "ci-avnet@example.com"
          git config --global user.name "CI Avnet"
          bitbake ${{ github.event.inputs.yocto-image }}
      - uses: hkusu/s3-upload-action@v2.1.0
        id: s3-upload
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: 'iotconnect-sdk-images'
          file-path: STM32MP157_IoTC_kirkstone/build-openstlinuxweston-stm32mp1/tmp-glibc/deploy/images/stm32mp1/${{ github.event.inputs.yocto-image }}-stm32mp157.tsv
          destination-dir: '/'
          bucket-root: 'sdk-images'
          public: true
          output-file-url: 'true'
