name: build-and-long-test

on:
  workflow_dispatch:
jobs:

#  start-self-hosted-runner:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout simplecore-tools
#        uses: actions/checkout@v4.1.1
#        with:
#          ssh-key: ${{ secrets.PRIVATE_KEY }}
#      - name: Start VM
#        timeout-minutes: 1440
#        id: start-vm
#        shell: bash
#        run: |
#          # Login Azure command line
#          az login --service-principal --username ${{ secrets.AZURE_USER_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }} --password ${{ secrets.AZURE_USER_TOKEN }}
#          export AZ_BEARER=$(az account get-access-token --query accessToken -o tsv --subscription ${{ secrets.AZURE_VM_SUBSCRIPTION_ID }})
#          $GITHUB_WORKSPACE/scotty/scripts/start-vm \
#            "${{ secrets.AZURE_VM_SUBSCRIPTION_ID }}" \
#            "${{ secrets.AZURE_VM_RESSOURCE_GROUP_NAME }}" \
  build-docker-msc-sm2s-imx8plus:
    if: ${{ github.event.inputs.build-docker == 'true' }}
    runs-on: [self-hosted, build]
    steps:
      - name: Checkout simplecore-tools
        uses: actions/checkout@v4.1.1
        with:
          path: 'yocto-layers'
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Prepare Docker Image
        if: github.ref_name == 'kirkstone'
        run: |
          ssh-keyscan -p 9418 -t rsa msc-git02.msc-ge.com >> ~/.ssh/known_hosts
          git clone ssh://gitolite@msc-git02.msc-ge.com:9418/msc_ol99/docker-msc-ldk
          ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
          cd docker-msc-ldk
          git checkout v1.11.0
          sed -i '/COPY rootfs\/home\/.ssh\/id_rsa/d' Dockerfile
          mkdir src
      - name: Prepare Docker Image
        if: github.ref_name == 'hardknott'
        run: |
          ssh-keyscan -p 9418 -t rsa msc-git02.msc-ge.com >> ~/.ssh/known_hosts
          git clone ssh://gitolite@msc-git02.msc-ge.com:9418/msc_ol99/docker-msc-ldk
          ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
          cd docker-msc-ldk
          git checkout v1.9.0
          sed -i '/COPY rootfs\/home\/.ssh\/id_rsa/d' Dockerfile
          mkdir src
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PKG_PAT}}
      - name:  Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: docker-msc-ldk
          push: true
          tags: ghcr.io/avnet-iotconnect/meta-iotconnect/msc-iocto-sdk-kirkstone:latest

  clean:
    runs-on: [self-hosted, build]
    if: always()
    needs:
      [
        build-yocto
      ]
    steps:
      - name: "clean build dir"
        run: |
          rm -rf docker-msc-ldk/

 # stop-self-hosted-runner:
 #   runs-on: ubuntu-latest
 #   needs:
 #     [
 #       start-self-hosted-runner,
 #     ]
 #   if: always()
 #   env:
 #   steps:
 #     - name: Checkout simplecore-tools
 #       uses: actions/checkout@v4.1.1
 #       with:
 #         ssh-key: ${{ secrets.PRIVATE_KEY }}
 #     - name: Stop VM composite
 #       uses: ./.github/ci-scripts/stop-self-hosted-runner
